### PR TITLE
Fix large title headers

### PR DESCRIPTION
**Pull request by WDKFernando**
you have to add `self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;` to `- (instancetype)init`  to fix the large titles. This solution worked for me on my iPhone 6 on iOS 12.4. No other devices tested.

### CODE REVIEW

**Comment by ShyMemoriees** [comment]
Do you use shuffle?

**Comment by WDKFernando** [comment]
yeah :)

**Comment by ShyMemoriees** [comment]
I already built something in that disables it, doesn’t work with shuffle though

**Comment by WDKFernando** [comment]
My solution works also with shuffle. You can try it out if you want to. If not, then not.
At least now I know why in your tweaks prefs the headers weren't fixed.

**Pull request closed without merging**
